/*
** Initial development used both a windows/bash OS and Linux OS
** To continue to have the ability to develop using Linux, please
** do not remove this file. If project is to be deprecated with
** single developer to maintain && Linux not used, it can be removed
*/




language: node_js

node_js:
  - 'node'
  - 'lts/*'

script:
  - node ./internals/scripts/generate-templates-for-linting
  - npm test -- --maxWorkers=4
  - npm run build

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

notifications:
  email:
    on_failure: 'https://keithturnerb@gmail.com'
    on_success: 'https://keithturnerb@gmail.com'
    
after_success: 'npm run coveralls'

cache:
  directories:
    - node_modules
